# example for postgres
# source: https://github.com/lukebfox/nix-flake-templates/blob/81bd61552dd12b3e9b9b56e9387111c62734a961/elixir/phoenix/docker-compose.yml
services:
  postgres:
    container_name: container-pg
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
